services:
  - type: web
    name: n8n-app
    env: docker
    image:
      url: docker.n8n.io/n8nio/n8n:latest
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        sync: false
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1