FROM docker.io/n8nio/n8n:latest

ENV PORT="5678" \
    N8N_PORT="5678" \
    N8N_PROTOCOL="https" \
    N8N_HOST="n8n-app.onrender.com" \
    N8N_WEBHOOK_URL="https://n8n-app.onrender.com/" \
    N8N_PROXY_HOPS="1" \
    N8N_RUNNERS_ENABLED="true" \
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS="true" \
    GENERIC_TIMEZONE="UTC" \
    TZ="UTC" \
    DB_TYPE="postgresdb" \
    DB_POSTGRESDB_HOST="aws-0-ap-northeast-2.pooler.supabase.com" \
    DB_POSTGRESDB_PORT="5432" \
    DB_POSTGRESDB_DATABASE="postgres" \
    DB_POSTGRESDB_USER="postgres.zxtwazynjcucxvdtisqw" \
    DB_POSTGRESDB_SCHEMA="public" \
    DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED="false"
