services:
  - type: web
    name: n8n-app
    runtime: image
    plan: starter
    image:
      url: docker.io/n8nio/n8n:latest
    healthCheckPath: /healthz
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: n8n-app.onrender.com
      - key: N8N_WEBHOOK_URL
        value: https://n8n-app.onrender.com/
      - key: N8N_PROXY_HOPS
        value: "1"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: TZ
        value: UTC
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-ap-northeast-2.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.zxtwazynjcucxvdtisqw
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"